### ISSUE TITLE
expanding unsupported fields returns empty data

### ISSUE THREAD

**Issue by hhartz** [Turbasen/Turbasen#97]
e.g. `lister/?expand=grupper` returns

`{
 "documents": [],
 "count": 0,
 "total": 0
}`

**Comment by geekus** [comment]
Seems like expanding supported fields also returns empty doc list. `lister/?expand=bilder`

So probably just expanding fields in general, when not querying a specific object is causing this.

**Comment by Starefossen** [comment]
Yes, expanding is not yet supported for collections for performance reasons.

**Comment by geekus** [comment]
Still, passing the query params should probably not result in returning an empty result, but rather be ignored, and just return the same result as when not passing the param?

**Comment by Starefossen** [comment]
Yeah... the thing is that `?expand?` is interpreted as a query parameter by [`mongo-querystring`](https://github.com/Turistforeningen/node-mongo-querystring). This needs to be added to the mq blacklist to prevent it from affecting the query.

**Comment by geekus** [comment]
And that would affect requests to `/type/objectid` which supports expand, and prevent it from working?

**Comment by Starefossen** [comment]
No, it would not. `/type/objectid` does not use the mq so adding it to the blacklist would be safe.
